### ISSUE TITLE
Docker manifest for armv8

### ISSUE THREAD

**Issue by nizrdev** [chtake/pi-wol#513]
Currently your docker image is only available to armv7. Are there any plans for armv8 since I can't run pi-wol on my raspberry pi 4?

**Comment by scottdetoffol** [comment]
I came here with the same question, would like to run this on my raspberry pi (Raspberry Pi 4 Model B Rev 1.5)

**Comment by chtake** [comment]
The develop build already has a arm64 docker image. Can you please check if the [develop-latest](https://hub.docker.com/layers/chtake/pi-wol/develop-latest/images/sha256-84e7c57a6fe7bdaa0768a87037f7d5de6b0e1448dcc6e18045cb5f0ffd8d8953?context=explore) tag works on your rpi? Unfortunately I can not test it because I do not have an RPI4. If it's working for you, I will create a new release to add this to the main branch.

**Comment by nizrdev** [comment]
The devlop-latest tag is not working. Docker compose says it needs an arm64/v8 manifest but currently there is only one for arm64 and armv7
" no matching manifest for linux/arm64/v8 in the manifest list entries "

**Comment by nizrdev** [comment]
Please dont ask me why I have not seen "develop" in your tag. I always tried to solve the problem just with "latest" tag. Anyways: "develop-latest" solved my problem, thank you very much. The application works fine, waking my pc is working reliable :)

**Comment by chtake** [comment]
Thank you for your reply. I created a release with arm64 support. It should now work also with the normal **latest** tag.

**Comment by nizrdev** [comment]
no problem, latest tag now works fine, too
